In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
df_train = pd.read_csv('/kaggle/London/train.csv')
df_test = pd.read_csv('/kaggle/London/test.csv')
df_sub = pd.read_csv('/kaggle/London/sample_submission.csv')

In [12]:
df_train.isna().sum()

ID                         0
fullAddress                0
postcode                   0
country                    0
outcode                    0
latitude                   0
longitude                  0
bathrooms              48479
bedrooms               24843
floorAreaSqM           13806
livingRooms            37040
tenure                  5721
propertyType             508
currentEnergyRating    56814
sale_month                 0
sale_year                  0
price                      0
dtype: int64

In [14]:
df_train = df_train.drop(['ID', 'fullAddress', 'country', 'postcode'], axis = 1)
df_test = df_test.drop(['ID', 'fullAddress', 'country', 'postcode'], axis = 1)

In [16]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 266325 entries, 0 to 266324
Data columns (total 13 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   outcode              266325 non-null  object
 1   latitude             266325 non-null  float64
 2   longitude            266325 non-null  float64
 3   bathrooms            217846 non-null  float64
 4   bedrooms             241482 non-null  float64
 5   floorAreaSqM         252519 non-null  float64
 6   livingRooms          229285 non-null  float64
 7   tenure               260604 non-null  object
 8   propertyType         265817 non-null  object
 9   currentEnergyRating  209511 non-null  object
 10  sale_month           266325 non-null  int64
 11  sale_year            266325 non-null  int64
 12  price                266325 non-null  int64
dtypes: float64(6), int64(3), object(4)
memory usage: 26.4+ MB

In [17]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16547 entries, 0 to 16546
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   outcode              16547 non-null  object
 1   latitude             16547 non-null  float64
 2   longitude            16547 non-null  float64
 3   bathrooms            13923 non-null  float64
 4   bedrooms             15172 non-null  float64
 5   floorAreaSqM         14541 non-null  float64
 6   livingRooms          14452 non-null  float64
 7   tenure               15957 non-null  object
 8   propertyType         16380 non-null  object
 9   currentEnergyRating  15050 non-null  object
 10  sale_month           16547 non-null  int64
 11  sale_year            16547 non-null  int64
dtypes: float64(6), int64(2), object(4)
memory usage: 1.5+ MB

In [18]:
df_test.isna().sum()

outcode                   0
latitude                  0
longitude                 0
bathrooms              2624
bedrooms               1375
floorAreaSqM           2006
livingRooms            2095
tenure                  590
propertyType            167
currentEnergyRating    1497
sale_month                0
sale_year                 0
dtype: int64

In [20]:
df_train.isna().sum()

outcode                    0
latitude                   0
longitude                  0
bathrooms              48479
bedrooms               24843
floorAreaSqM           13806
livingRooms            37040
tenure                  5721
propertyType             508
currentEnergyRating    56814
sale_month                 0
sale_year                  0
price                      0
dtype: int64

In [21]:
df_train['bathrooms'].value_counts()

bathrooms
1.0    143432
2.0     58789
3.0     11786
4.0      2662
5.0       706
6.0       321
7.0       103
8.0        33
9.0        14
Name: count, dtype: int64

In [22]:
df_test['bathrooms'].value_counts()

bathrooms
1.0    8959
2.0    3944
3.0     761
4.0     170
5.0      57
6.0      23
7.0       5
8.0       3
9.0       1
Name: count, dtype: int64

In [24]:
df_train.loc[df_train['bathrooms'].isna(), 'bathrooms'] = np.random.range(a = [1.0, 2.0, 3.0, 4.0], size = df_train['Bathrooms'].isna().sum(), p = [5.0, 2.0, 1.0, 1.0])
df_test.loc[df_test['bathrooms'].isna(), 'bathrooms'] = np.random.range(a = [1.0, 2.0, 3.0, 4.0], size = df_test['Bathrooms'].isna().sum(), p = [5.0, 2.0, 1.0, 1.0])

AttributeError: module 'numpy.random' has no attribute 'range'